# Generated by Django 4.0.5 on 2022-06-30 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmpList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('empid', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=300)),
                ('age', models.CharField(max_length=4)),
                ('emplist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empcrud.emplist')),
            ],
        ),
    ]
