# Generated by Django 4.0.5 on 2022-07-01 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empcrud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emplist',
            name='age',
            field=models.CharField(default='', max_length=4),
        ),
        migrations.AddField(
            model_name='emplist',
            name='position',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.DeleteModel(
            name='Details',
        ),
    ]
