# Generated by Django 4.0.5 on 2022-07-14 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empcrud', '0002_emplist_age_emplist_position_delete_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emplist',
            name='empid',
            field=models.DecimalField(decimal_places=0, max_digits=5, max_length=4),
        ),
    ]
