# Generated by Django 4.0.5 on 2022-07-20 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empcrud', '0005_alter_emplist_age_alter_emplist_empid'),
    ]

    operations = [
        migrations.AddField(
            model_name='emplist',
            name='emp_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
