# Generated by Django 4.0.5 on 2022-07-14 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoginUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('empid', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
