# Generated by Django 4.0.5 on 2022-07-18 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoginUser',
        ),
    ]
